# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='static/post_images'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='image',
            field=models.ImageField(upload_to='static/post_images'),
        ),
    ]
