# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180313_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post/images'),
        ),
        migrations.AlterField(
            model_name='postgallery',
            name='image',
            field=models.ImageField(upload_to='post/images'),
        ),
    ]
